export default Object.freeze({
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_ROOT: 'HOME_ROOT',
  HOME_SCREEN: 'HOME_SCREEN',
  FETCH_DATA_SCREEN: 'FETCH_DATA_SCREEN',
  FORM_SCREEN: 'FORM_SCREEN',
  MAIN_TABS_ROOT: 'MAIN_TABS_ROOT',
  MAIN_DRAWER_ROOT: 'MAIN_DRAWER_ROOT',
  FORGOTPASSWORD_SCREEN: 'FORGOTPASSWORD_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  ALERT: 'ALERT', // Do not redirect!
});
